### ISSUE TITLE
The api didn't give the id of 有效情报值

### ISSUE THREAD

**Issue by LittleNightmare** [penguin-statistics/backend#15]
### URL
`https://penguin-stats.io/PenguinStats/api/items`

### Steps to reproduce
try to get id from  [item api](https://penguin-stats.io/PenguinStats/api/items)
then, use it to send data of 有效情报值

### What is expected?
get id and then report data

### What is actually happening?
the program didn't find the id

---
will you support it soon? or you don't want to count this item

**Comment by Strontium233** [comment]
This is a special item that is a constant amount of loot among all activity stages, where 1有效情报值=1pt of sanity. Thus we don't offer information about this special activity item. Please refer to the sanity points consumed for each stage.
