### ISSUE TITLE
汇报API加个uploader

### ISSUE THREAD

**Issue by DavidDiao** [penguin-statistics/backend#2]
我在试着写自动上传的东西 poi-statistics的数据收集是会收集上传的插件名称和版本号的 我觉得你们也可以整一个
~~之后无聊可以写写贡献排名x~~

**Comment by DavidDiao** [comment]
啊 写好了（虽然很粗糙就是了）
https://github.com/DavidDiao/ArkReport
今天有空在泥潭发个贴x

**Comment by AlvISsReimu** [comment]
我去在汇报API里加上source和version~还有哪些需要加的吗？

**Comment by DavidDiao** [comment]
source是昵称 version是上传器+版本号吗
（游戏发包会传玩家昵称 但是好像直接收集不合适）

**Comment by AlvISsReimu** [comment]
我倾向于source是放来源于人工汇报、截图还是您的上传器，version放版本号。玩家的昵称感觉可以再新建别的attribute？我这边以后也有可能会加上用户名之类的，这些识别用户的属性感觉可以放在一起

**Comment by DavidDiao** [comment]
emmm那行啊 ~~我可以光明正大咕ui了~~
（要上传用户昵称的话我还需要整一个是否同意收集

**Comment by AlvISsReimu** [comment]
不同意的话我们就写anonymous或者用别的什么特征来代替（真的好嘛（

**Comment by DavidDiao** [comment]
（我觉得没毛病

**Comment by AlvISsReimu** [comment]
加好了 希望有硬核刀客塔能来试试抓包上传w
