### ISSUE TITLE
关于“物品掉落分时查询”的问题

### ISSUE THREAD

**Issue by guoh064** [penguin-statistics/backend#24]
请问“物品掉落分时查询”这个功能实装以后，是否可以查询近三个月/近一个月等时间段内的掉落情况了？
（有些怀疑丫丁暗改掉率，但是好像企鹅物流目前的算法都是从开服时的数据一直滚到现在？）

**Comment by pingplug** [comment]
我应该把这个issue提交到这里的:  #https://github.com/penguin-statistics/frontend-v2/issues/276

> 以DM6为例，企鹅物流上统计的掉落概率是69%，我在第一天刷的时候10把掉落了8个，虽然结果偏高但是该事件发生的概率也有22%
> 
> 最近两天刷DM6的时候，连续出现10把掉落5个的情况（然后我就刷DM8去了），如果关卡掉落概率仍是69%，这一事件发生的概率只有11%，而且连续发生了两天
> 
> 我98%的自信认为DM6的关卡概率发生了变化，而企鹅物流的统计未能及时反映这次变化
> 
> 很明显可以看到，企鹅物流这两天DM6的数据量很少（远少于1000，而目前总样本量有2200多），如果没有一个近期样本权重更高的结果，将会误导很多依赖该数据的网站

**Comment by GalvinGao** [comment]
我们已于一个月前上线了“高级查询”功能，支持任意时间段的任意数据查询；请于 http://penguin-stats.io/advanced 使用此功能~

功能已实现，将关闭 Issue
（如果有建议的话欢迎新开一个 Issue 反馈哦~）
