### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by AlvISsReimu** [penguin-statistics/backend#30]
Tomcat, nginx, mongodb

**Comment by GalvinGao** [comment]
Pinging on this ;)

This shall be pretty much useful for getting out `staging` environment up and running.

**Comment by amenomori** [comment]
Is this issue still remain open? I tried to work on this when I found the repo: backend-docker. 

Remain this one here open is confusing.

**Comment by GalvinGao** [comment]
> Is this issue still remain open? I tried to work on this when I found the repo: backend-docker.
> 
> Remain this one here open is confusing.

Hi Amenomori!
Yes one of the contributors was working on the backend-docker repo, however the status of another repo is currently unmaintained and the contributor at such repo might not have enough time to complete such task.
If you want to get hands on such repo you are more than welcome to do so, however I don't really know if the content of the repo is still up to date :(

Thanks for your interest in advance!
