### ISSUE TITLE
数据修正请求

### ISSUE THREAD

**Issue by dantmnf** [penguin-statistics/backend#57]
https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper 在实现 v2 API 掉落数量验证的过程中，错误地将活动掉落从最终提交列表中移除<sup>[1]</sup>。

请考虑从自 2020 年 6 月至今（包括当前活动）的活动掉落样本中移除来自 ArknightsAutoHelper 的样本。

\[1\]: https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/blob/18ac87a1c67d495aca385107978c4815ecc95936/penguin_stats/reporter.py#L140 ，由于 https://github.com/penguin-statistics/frontend-v2/issues/175 ，活动掉落的数量由 ArknightsAutoHelper 自行验证，并通过一个 dirty hack 跳过使用 API 数据进行的验证。

---

另：修复过程中产生了

* 36ec48da66107138d2bafff1710e807455005435846080c28a035730b1c7a7c1
* 71a127e8798d1508a65aa382082eefe46f29ae54d530c2ab18cabd9283aca83d
* 3b31ca263cbccfca6039d16650aed0bf5aad2ec3930118ac32c40ea8038ecc3d

等多个包含活动掉落的 report，但似乎没有反映在在前端中查询到的数量中，希望确认是否包含活动掉落

**Comment by AlvISsReimu** [comment]
感谢反馈，已经移除了从国服沃伦姆德活动开始source为`ArknightsAutoHelper`的总计4720个样本（stageId为`act.*`的活动关卡汇报）。
关于当前的感谢庆典，请问需要移除直到当前时间点的所有汇报吗（目前7k+）？如果您那边的bug已修复，是否在某个时间点后或者某些version的样本可以得以保留？这些汇报的version分布如下，供参考：
```
/* 1 */
{
    "_id" : "UNKNOWN",
    "count" : 3434.0
}

/* 2 */
{
    "_id" : "master+20200823-19-g778e415",
    "count" : 951.0
}

/* 3 */
{
    "_id" : "master+814fbb4-ci",
    "count" : 670.0
}

/* 4 */
{
    "_id" : "master+20200823-25-ga641cf8",
    "count" : 609.0
}

/* 5 */
{
    "_id" : "master+20200823-25-ga641cf8-dirty",
    "count" : 496.0
}

/* 6 */
{
    "_id" : "master+a641cf8-ci",
    "count" : 269.0
}

/* 7 */
{
    "_id" : "master+20200823-24-g814fbb4",
    "count" : 166.0
}

/* 8 */
{
    "_id" : "master+20200823-19-g778e415-dirty",
    "count" : 132.0
}

/* 9 */
{
    "_id" : "master+778e415-ci",
    "count" : 106.0
}

/* 10 */
{
    "_id" : "master+20200823-24-g814fbb4-dirty",
    "count" : 102.0
}

/* 11 */
{
    "_id" : "master+20200823-20-g270939c-dirty",
    "count" : 74.0
}

/* 12 */
{
    "_id" : "master+20200808-dirty",
    "count" : 70.0
}

/* 13 */
{
    "_id" : "master+20200823-16-g933e427",
    "count" : 44.0
}

/* 14 */
{
    "_id" : "master+20200823-27-g26d711c-dirty",
    "count" : 16.0
}

/* 15 */
{
    "_id" : "master+20200823-13-g7338bdf",
    "count" : 8.0
}
```

**Comment by dantmnf** [comment]
尝试修复 bug 的 commit 为 https://github.com/ninthDevilHAUNSTER/ArknightsAutoHelper/commit/a641cf8d5523a4acd9ce7b585fb3b0c627917c3e ，对应以下三个版本，如果可以确认有产生包含当期活动掉落的汇报就可以保留。
```
/* 4 */
{
    "_id" : "master+20200823-25-ga641cf8",
    "count" : 609.0
}

/* 5 */
{
    "_id" : "master+20200823-25-ga641cf8-dirty",
    "count" : 496.0
}

/* 6 */
{
    "_id" : "master+a641cf8-ci",
    "count" : 269.0
}
```

**Comment by AlvISsReimu** [comment]
谢谢，已移除其余version的掉落样本。目前看来`version = UNKNOWN`的样本还在增加中，我们会继续对其进行移除。

**Comment by dantmnf** [comment]
`version = UNKNOWN` 有部分是通过 github download zip 打包下载的，目前也想不出有什么办法加个版本号进去。

**Comment by GalvinGao** [comment]
> `version = UNKNOWN` 有部分是通过 github download zip 打包下载的，目前也想不出有什么办法加个版本号进去。

这个的话感觉可以检测下如果此版本不是正常的stable发版，那么就直接显示一条提示下载stable版本？
另一个方案就是将default branch设置为master、新的开发全部在dev branch完成，然后在每次release前直接将dev的commit merge进master后，于master发布release，这样一般的使用者真的打包下载了也只会下载stable的内容
希望有帮到您 :D
