### ISSUE TITLE
内部优化：错误信息报错统一化

### ISSUE THREAD

**Issue by ChoKhoOu** [penguin-statistics/backend#62]
目前企鹅的异常信息较为混乱，缺乏统一的管理。
如：
```java
	public ResponseEntity<AdvancedQueryResponse> getAdvancedResultHelper(AdvancedQueryRequest advancedQueryRequest,
			HttpServletRequest request) {
                            // 省略
		advancedQueryRequest.getQueries().forEach(singleQuery -> {
			try {
		               // 省略
				BasicQueryResponse queryResponse = queryMapper.elementsToBasicQueryResponse(singleQuery, elements);
				results.add(queryResponse);
			} catch (TimeoutException toEx) {
				log.error("TimeoutException in executeAdvancedQueries: ", toEx);
			} catch (ExecutionException exeEx) {
				log.error("ExecutionException in executeAdvancedQueries: ", exeEx);
			} catch (Exception ex) {
				log.error("Error in executeAdvancedQueries: ", ex);
			}
		});
		AdvancedQueryResponse advancedQueryResponse = new AdvancedQueryResponse(results);
		return new ResponseEntity<AdvancedQueryResponse>(advancedQueryResponse, HttpStatus.OK);
	}

```
如上图代码。当查询结果超时时，`queryMapper.elementsToBasicQueryResponse`就会throw一个TimeoutException，而上图代码catch住该异常后，仅仅是log了一个error日志，再无其他操作。在该业务逻辑的最后，直接将emptyList返回给上层代码，最终返回给前端。
而实际上，当成功调用`queryMapper.elementsToBasicQueryResponse`时，其最终返回的结果中，是很有可能查询到数据的。
这对用户非常的不友好。

对于这种情况的代码，并不仅仅存在于某一处，在企鹅中也有其他类似的情况。 

针对当前对异常的混乱处理，我将对企鹅中整体的异常体系进行重构，对异常进行统一化。

具体会在最上层异常分为两大类：

1. ServiceException: 当前服务因为某些原因挂了，或者RPC超时，又或者是DB异常（锁， 超时）等等的一些源于系统内部的异常，将会使用此异常进行抛出。处理该异常时，我们将会统一给前端传 ：“服务繁忙"的字眼。 
```java
	public ResponseEntity<AdvancedQueryResponse> getAdvancedResultHelper(AdvancedQueryRequest advancedQueryRequest,
			HttpServletRequest request) {
		// 省略
		advancedQueryRequest.getQueries().forEach(singleQuery -> {
			try {
				// 省略
				BasicQueryResponse queryResponse = queryMapper.elementsToBasicQueryResponse(singleQuery, elements);
				results.add(queryResponse);
			} catch (TimeoutException toEx) {
				// example
				throw new ServiceException("TimeoutException in executeAdvancedQueries.",toEx);
			} 
		});
		AdvancedQueryResponse advancedQueryResponse = new AdvancedQueryResponse(results);
		return new ResponseEntity<AdvancedQueryResponse>(advancedQueryResponse, HttpStatus.OK);
	}
```
2. BusinessException: 当用户操作错误、数据库中查找不到数据、又或者某些参数不合法，等等的一些源于用户这边的错误，导致业务逻辑需要终止的异常，将会使用此异常进行抛出。在这个异常中，我们还会给出准确的tips返回给用户，以告知用户错误原因。

对于ServiceException，在内部中，我们会把详细的堆栈信息打印出来以便于开发人员以及运维定位问题。而对于BusinessException，我们仅需log简单的一些msg日志即可

**Comment by GalvinGao** [comment]
感谢大佬！
有一点想着重强调一下，就是不管是什么样的Exception，应返回**错误Type**（便于企鹅自己的前端本地化错误消息），同时附带一段无需本地化的、合适的、相对简短的错误消息（便于调试、以及可使第三方API调用者也相对清晰地知道error的含义），例如：

- 数据库返回超时 `{"error": {"type": "DBTimeoutException", "message": "database query exceeded 5000ms limit"}}`
- 不合法的Server参数 `{"error": {"type": "InvalidServerArgumentException", "message": "provided param 'server' is invalid"}}`

除此之外，之前的API默认会在出现Exception的时候返回空列表，但是如果我们需要支持错误返回，那么直接更改之前的响应体结构很可能会导致第三方API调用者爆炸x。所以可能这部分响应的返回还需要再加以斟酌🤔

**Comment by ChoKhoOu** [comment]
> 感谢大佬！
> 有一点想着重强调一下，就是不管是什么样的Exception，应返回**错误Type**（便于企鹅自己的前端本地化错误消息），同时附带一段无需本地化的、合适的、相对简短的错误消息（便于调试、以及可使第三方API调用者也相对清晰地知道error的含义），例如：
> 
> * 数据库返回超时 `{"error": {"type": "DBTimeoutException", "message": "database query exceeded 5000ms limit"}}`
> * 不合法的Server参数 `{"error": {"type": "InvalidServerArgumentException", "message": "provided param 'server' is invalid"}}`
> 
> 除此之外，之前的API默认会在出现Exception的时候返回空列表，但是如果我们需要支持错误返回，那么直接更改之前的响应体结构很可能会导致第三方API调用者爆炸x。所以可能这部分响应的返回还需要再加以斟酌🤔

问一下，目前返回的消息中，是已经有`type` 这个属性了嘛？
 `{"error": {"type": "DBTimeoutException", "message": "database query exceeded 5000ms limit"}}`  
似乎目前并没有errorCode的设计，但直接用type去识别本地化消息是不是有点不太好(

另外就是，企鹅目前是在前端去进行本地化错误消息嘛？


🤔最后就是，目前这样做的话，是大概率会影响到所有的API， 这里我再去跟阿包商量一下。

**Comment by GalvinGao** [comment]
> > 感谢大佬！
> > 有一点想着重强调一下，就是不管是什么样的Exception，应返回**错误Type**（便于企鹅自己的前端本地化错误消息），同时附带一段无需本地化的、合适的、相对简短的错误消息（便于调试、以及可使第三方API调用者也相对清晰地知道error的含义），例如：
> > 
> > * 数据库返回超时 `{"error": {"type": "DBTimeoutException", "message": "database query exceeded 5000ms limit"}}`
> > * 不合法的Server参数 `{"error": {"type": "InvalidServerArgumentException", "message": "provided param 'server' is invalid"}}`
> > 
> > 除此之外，之前的API默认会在出现Exception的时候返回空列表，但是如果我们需要支持错误返回，那么直接更改之前的响应体结构很可能会导致第三方API调用者爆炸x。所以可能这部分响应的返回还需要再加以斟酌🤔
> 
> 问一下，目前返回的消息中，是已经有`type` 这个属性了嘛？
> `{"error": {"type": "DBTimeoutException", "message": "database query exceeded 5000ms limit"}}`
> 似乎目前并没有errorCode的设计，但直接用type去识别本地化消息是不是有点不太好(

现在返回的消息里没有这样的属性呢（所以会产生兼容问题

> 另外就是，企鹅目前是在前端去进行本地化错误消息嘛？

是的；不过现在做的错误信息也不太多，只有像服务器超时、服务暂时因部署不可用之类的，没有用到errorCode，只是检测返回的http status code

> 🤔最后就是，目前这样做的话，是大概率会影响到所有的API， 这里我再去跟阿包商量一下。

嗯嗯，是肯定会影响的；感觉就只有加个v3这种才能解决了x
