### ISSUE TITLE
Can you add new 常驻-生于黑夜 section in the chapter stats and the corresponding item stats? 

### ISSUE THREAD

**Issue by jznling** [penguin-statistics/backend#69]
The new version of the Arknights is already released for 4 days. Still haven't seen the corresponding updates in penguin-stats for the permanent activity - 生于黑夜. DM-6 to 8 still only had the stats up to April 8th. And the users have no place to upload their stats for the nowadays DM activity. Just wanna get a clue when it will be added to penguin-stats?

**Comment by GalvinGao** [comment]
Hi! We have added such stage several days ago. The delay was introduced by compatibility issues with the stageId we've used, but we have successfully managed to fix that.

Thanks for your report!
