### ISSUE TITLE
(error) [Ajax] failed Error: Request failed with status code 500

### ISSUE THREAD

**Issue by Ericli0708** [penguin-statistics/backend#70]
### URL
`https://penguin-stats.io/report/stage/act18d3_zone1/act18d3_09`

### What is actually happening?
2021-05-10 以及 2021-05-11 早上9点左右都会自动出现这个问题无法汇报掉落，本地网络正常。

---
(error) [Ajax] failed Error: Request failed with status code 500
    exports https://penguin-stats.io/js/chunk-vendors.0856f51d.js:1
    exports https://penguin-stats.io/js/chunk-vendors.0856f51d.js:7
    onreadystatechange https://penguin-stats.io/js/chunk-vendors.0856f51d.js:34
    r https://penguin-stats.io/js/chunk-vendors.0856f51d.js:7
chunk-vendors.0856f51d.js:7:429139
    Rt https://penguin-stats.io/js/chunk-vendors.0856f51d.js:7
    value https://penguin-stats.io/js/app.e10a9b45.js:1
    value https://penguin-stats.io/js/app.e10a9b45.js:1
    9efd https://penguin-stats.io/js/app.e10a9b45.js:1

**Comment by ChoKhoOu** [comment]
最近几天呢， 是不是每天九点左右都还是不行？
